# Get editor completions based on the config schema

format = '$character$directory($git_branch)[✘](bold yellow) '

# Inserts a blank line between shell prompts
add_newline = false

# Replace the '❯' symbol in the prompt with '➜'✗
[character] # The name of the module we are configuring is 'character'
success_symbol = '[➜](bold green)' # The 'success_symbol' segment is being set to '➜' with the color 'bold green'
error_symbol = "[➜](bold #bf616a)"
vicmd_symbol = "[➜](bold #5e81ac)"

[directory]
truncation_length=1
home_symbol="roy"

[battery]
disabled = true

[cmd_duration]
format = "[$duration]($style)"
style = 'bright-black'

[git_branch]
style = "#2e3440"# #4F8FE5
format = '[git:\(](fg:#d6acff bold)[($branch)](fg:#E55953 bold)[\) ](fg:#d6acff bold)'


[nodejs]
disabled = true

[package]
disabled = true

[ruby]
disabled = true

[lua]
disabled = true
